export function previewPage(config: {
  token: string;
  deviceId: string;
}): string {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Orbit · SDK preview</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#f4eddd;color:#242824;font:15px/1.5 ui-sans-serif,system-ui,sans-serif}main{max-width:960px;margin:0 auto;padding:42px 24px}header{display:flex;justify-content:space-between;align-items:center;border-bottom:2px solid;padding-bottom:18px}.brand{font-size:22px;font-weight:800;letter-spacing:-1px}.tag{font:11px ui-monospace,monospace;letter-spacing:1.5px;text-transform:uppercase}.workspace{display:grid;grid-template-columns:1fr 300px;gap:60px;align-items:center;min-height:500px}h1{font-size:34px;line-height:1.1;letter-spacing:-1.5px;margin:0 0 20px}p{color:#676c64}.device{display:flex;align-items:center;justify-content:center;min-height:370px}canvas{width:min(320px,70vw);height:min(320px,70vw);border-radius:50%;background:#09090c;outline:3px solid #242824;border:12px solid #d5dbb7;box-shadow:0 14px 0 #929b71,0 17px 0 2px #242824;touch-action:none;cursor:crosshair}.controls{display:flex;gap:10px;flex-wrap:wrap;margin:24px 0}button,label{border:2px solid;border-radius:10px;padding:10px 14px;background:#dce9b4;box-shadow:2px 3px 0 #242824;color:#242824;font:inherit}button{cursor:pointer;touch-action:none}button:active{transform:translate(2px,3px);box-shadow:none}label{display:flex;align-items:center;gap:7px;background:#efd2f1}input{accent-color:#53487c}#status{font-size:12px;overflow-wrap:anywhere}code{font-size:12px}footer{border-top:2px solid;padding-top:18px;color:#676c64;font-size:12px}@media(max-width:720px){.workspace{grid-template-columns:1fr;gap:12px;padding:32px 0}.device{min-height:350px}}
</style></head><body><main><header><span class="brand">orbit.</span><span class="tag">SDK preview · virtual device</span></header><section class="workspace"><div class="device"><canvas id="screen" width="480" height="480" aria-label="Simulated Orbit touchscreen" tabindex="0"></canvas></div><div><h1>Your code.<br>Your character.</h1><p>Touch the screen to send input to your Bun program. Save your script to reload it with <code>bun --watch</code>.</p><div class="controls"><button id="talk">Hold talk</button><label><input id="mute" type="checkbox">Mute switch</label></div><p id="status" role="status">Connecting to simulator…</p></div></section><footer>Virtual touch, talk button and mute switch. These controls send input events; your program decides what they do.</footer></main><script id="orbit-config" type="application/json">${JSON.stringify(config).replaceAll('<', '\\u003c')}</script><script type="module" src="/preview.js"></script></body></html>`;
}
