import { build } from 'vite';
import react from '@vitejs/plugin-react';
import tailwindcss from '@tailwindcss/postcss';
import {
  copyFile,
  mkdir,
  readdir,
  access,
  readFile,
  writeFile,
} from 'node:fs/promises';
import { basename, dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import assert from 'node:assert/strict';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const out = join(root, 'dist/landing');
const config = {
  configFile: false,
  root: join(root, 'landing'),
  publicDir: false,
  plugins: [react()],
  resolve: {
    alias: { '@': root, 'next/link': join(root, 'landing/link.tsx') },
  },
  css: { postcss: { plugins: [tailwindcss()] } },
};

// Build just the shared landing and character, never the local lab or host.
await build({ ...config, build: { outDir: out, emptyOutDir: true } });
const renderDir = join(root, 'dist/landing-render');
await build({
  ...config,
  build: {
    ssr: join(root, 'landing/render.tsx'),
    outDir: renderDir,
    emptyOutDir: true,
  },
});
const { render } = await import(
  pathToFileURL(join(renderDir, 'render.js')).href
);
const markup = render();
assert(markup.includes('Take your'), 'Landing content did not render');
assert(
  !/href="\/(lab|companion|paper)([?"/])/.test(markup),
  'Local application link in public landing',
);
const template = await readFile(join(out, 'index.html'), 'utf8');
assert(template.includes('<!--orbit-markup-->'), 'Missing render placeholder');
await writeFile(
  join(out, 'index.html'),
  template.replace('<!--orbit-markup-->', markup),
);

// Public source checkout includes self-hosted fonts and their OFL notice.
const bundledFonts = await access(join(root, 'public/fonts.css')).then(() => true, () => false);
if (bundledFonts) {
  await mkdir(join(out, 'fonts'), { recursive: true });
  for (const file of await readdir(join(root, 'public/fonts'))) {
    await copyFile(join(root, 'public/fonts', file), join(out, 'fonts', file));
  }
  await copyFile(join(root, 'public/fonts.css'), join(out, 'fonts.css'));
} else {
// Reuse the exact self-hosted fonts generated by the normal vinext build.
const fontRoot = join(root, '.vinext/fonts');
let fontCss = '';
await mkdir(join(out, 'fonts'), { recursive: true });
for (const family of ['geist-', 'geist-mono-']) {
  const candidates = (await readdir(fontRoot)).filter((name) =>
    family === 'geist-'
      ? /^geist-[a-f0-9]+$/.test(name)
      : name.startsWith(family),
  );
  assert.equal(
    candidates.length,
    1,
    'Run the normal build with a clean font cache if the font version is ambiguous',
  );
  const css = await readFile(
    join(fontRoot, candidates[0], 'style.css'),
    'utf8',
  );
  const sources = [...css.matchAll(/url\(([^)]+)\)/g)].map((match) => match[1]);
  for (const source of sources)
    await copyFile(source, join(out, 'fonts', basename(source)));
  fontCss +=
    css.replace(
      /url\(([^)]+)\)/g,
      (_, source) => `url(/fonts/${basename(source)})`,
    ) + '\n';
}
await writeFile(join(out, 'fonts.css'), fontCss);
}
await mkdir(join(out, 'cad'), { recursive: true });
await copyFile(join(root, 'public/favicon.svg'), join(out, 'favicon.svg'));
await copyFile(
  join(root, 'public/cad/orbit-form-study.scad'),
  join(out, 'cad/orbit-form-study.scad'),
);
await writeFile(join(out, '_redirects'), '/play / 301\n/play/ / 301\n');
await writeFile(
  join(out, '_headers'),
  '/*\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: strict-origin-when-cross-origin\n\n/assets/*\n  Cache-Control: public, max-age=31536000, immutable\n\n/fonts/*\n  Cache-Control: public, max-age=31536000, immutable\n',
);
await writeFile(
  join(out, 'robots.txt'),
  'User-agent: *\nAllow: /\nSitemap: https://orbit.moon-bots.com/sitemap.xml\n',
);
await writeFile(
  join(out, 'sitemap.xml'),
  '<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>https://orbit.moon-bots.com/</loc></url></urlset>',
);
await writeFile(
  join(out, '404.html'),
  '<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Page not found — Orbit</title><style>body{background:#f8f2dc;color:#262534;font:18px system-ui;max-width:40rem;margin:15vh auto;padding:2rem}a{color:inherit}</style><h1>This page isn’t here.</h1><p><a href="/">Back to Orbit ↗</a></p></html>',
);
console.log(
  'Public landing built with rendered HTML, local fonts, CAD and Familiar.',
);
